# Configurações do Site
title: Gustavo Davel
tagline: Engenheiro de dados | Inteligência Artificial 
description: >-
  Blog pessoal e portfólio sobre Engenharia de dados e Inteligência Artificial.
url: "https://gustavogdavel.github.io"
baseurl: "/BlogPortifolio"

# Informações do Autor
author:
  name: Gustavo Davel
  email: gustavodavel@gmail.com
  github: gustavogdavel
  linkedin: https://www.linkedin.com/in/gustavogdavel/
  # twitter: seu-twitter

# Configurações de Build
markdown: kramdown
highlighter: rouge
permalink: /posts/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

# Paginação
paginate: 10
paginate_path: "/page/:num/"

# Coleções
collections:
  posts:
    output: true
    permalink: /posts/:year/:month/:day/:title/

# Configurações padrão
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Exclude arquivos do build
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md

# Timezone
timezone: America/Sao_Paulo

# Encoding
encoding: utf-8

# Sass
sass:
  style: compressed
